---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: test-kustomization
  namespace: flux-system
spec:
  interval: 30s
  path: ./infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: test-source
  targetNamespace: test

